# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lp_distance <- function(a, b, p) {
    .Call('MiniMiniMaxUQ_lp_distance', PACKAGE = 'MiniMiniMaxUQ', a, b, p)
}

find_K_hat <- function(xs, ys, p_norm = -1., min_dist = 1e-4) {
    .Call('MiniMiniMaxUQ_find_K_hat', PACKAGE = 'MiniMiniMaxUQ', xs, ys, p_norm, min_dist)
}

f_deviations <- function(xs, K_hat, x) {
    .Call('MiniMiniMaxUQ_f_deviations', PACKAGE = 'MiniMiniMaxUQ', xs, K_hat, x)
}

do_pointwise_uncertainty <- function(ys, deviations) {
    .Call('MiniMiniMaxUQ_do_pointwise_uncertainty', PACKAGE = 'MiniMiniMaxUQ', ys, deviations)
}

pointwise_uncertainty <- function(xs, ys, K_hat, x) {
    .Call('MiniMiniMaxUQ_pointwise_uncertainty', PACKAGE = 'MiniMiniMaxUQ', xs, ys, K_hat, x)
}

